### ISSUE TITLE
`end-of-line` in emacs config.

### ISSUE THREAD

**Issue by Honeypot95** [adimit/config#1]
Hi!

I come from reddit, and I know this is a personal repository, and not a project in itself, but since it is public, I thought of asking the following question:

In `config/newmacs/main.org`, in the `magit` section, the function `buffer-insert-at-end` does
```elisp
(goto-char (point-max))
(end-of-line)
```
Is there any case in which `(goto-char (point-max))` would not point to the last character, needing a `(end-of-line)` instruction after it?

**Comment by adimit** [comment]
Feel free to ask questions. Just, uh…, I'll be honest, I have no idea why I wrote that. I have the feeling there might've been an edge-case somewhere, but I wouldn't be able to reproduce it right now.
